/* NATURE */
export const GET_NATURES = "GET_NATURES"
export const GET_NATURES_SUCCESS = "GET_NATURES_SUCCESS"
export const GET_NATURES_FAIL = "GET_NATURES_FAIL"

export const ADD_NEW_NATURE = "ADD_NEW_NATURE"
export const ADD_NATURE_SUCCESS = "ADD_NATURE_SUCCESS"
export const ADD_NATURE_FAIL = "ADD_NATURE_FAIL"

export const UPDATE_NATURE = "UPDATE_NATURE"
export const UPDATE_NATURE_SUCCESS = "UPDATE_NATURE_SUCCESS"
export const UPDATE_NATURE_FAIL = "UPDATE_NATURE_FAIL"

export const DELETE_NATURE = "DELETE_NATURE"
export const DELETE_NATURE_SUCCESS = "DELETE_NATURE_SUCCESS"
export const DELETE_NATURE_FAIL = "DELETE_NATURE_FAIL"