/* TRANSFERT */
export const GET_TRANSFERTS = "GET_TRANSFERTS"
export const GET_TRANSFERTS_SUCCESS = "GET_TRANSFERTS_SUCCESS"
export const GET_TRANSFERTS_FAIL = "GET_TRANSFERTS_FAIL"

export const ADD_NEW_TRANSFERT = "ADD_NEW_TRANSFERT"
export const ADD_TRANSFERT_SUCCESS = "ADD_TRANSFERT_SUCCESS"
export const ADD_TRANSFERT_FAIL = "ADD_TRANSFERT_FAIL"

export const UPDATE_TRANSFERT = "UPDATE_TRANSFERT"
export const UPDATE_TRANSFERT_SUCCESS = "UPDATE_TRANSFERT_SUCCESS"
export const UPDATE_TRANSFERT_FAIL = "UPDATE_TRANSFERT_FAIL"

export const DELETE_TRANSFERT = "DELETE_TRANSFERT"
export const DELETE_TRANSFERT_SUCCESS = "DELETE_TRANSFERT_SUCCESS"
export const DELETE_TRANSFERT_FAIL = "DELETE_TRANSFERT_FAIL"