/* CATEGORIE */
export const GET_INVENTORY = "GET_INVENTORY"
export const GET_INVENTORY_SUCCESS = "GET_INVENTORY_SUCCESS"
export const GET_INVENTORY_FAIL = "GET_INVENTORY_FAIL"

export const ADD_NEW_INVENTORY = "ADD_NEW_INVENTORY"
export const ADD_INVENTORY_SUCCESS = "ADD_INVENTORY_SUCCESS"
export const ADD_INVENTORY_FAIL = "ADD_INVENTORY_FAIL"

export const UPDATE_INVENTORY = "UPDATE_INVENTORY"
export const UPDATE_INVENTORY_SUCCESS = "UPDATE_INVENTORY_SUCCESS"
export const UPDATE_INVENTORY_FAIL = "UPDATE_INVENTORY_FAIL"

export const DELETE_INVENTORY = "DELETE_INVENTORY"
export const DELETE_INVENTORY_SUCCESS = "DELETE_INVENTORY_SUCCESS"
export const DELETE_INVENTORY_FAIL = "DELETE_INVENTORY_FAIL"