/* COUNTRIE */
export const GET_COUNTRIES = "GET_COUNTRIES"
export const GET_COUNTRIES_SUCCESS = "GET_COUNTRIES_SUCCESS"
export const GET_COUNTRIES_FAIL = "GET_COUNTRIES_FAIL"

export const ADD_NEW_COUNTRIE = "ADD_NEW_COUNTRIE"
export const ADD_COUNTRIE_SUCCESS = "ADD_COUNTRIE_SUCCESS"
export const ADD_COUNTRIE_FAIL = "ADD_COUNTRIE_FAIL"

export const UPDATE_COUNTRIE = "UPDATE_COUNTRIE"
export const UPDATE_COUNTRIE_SUCCESS = "UPDATE_COUNTRIE_SUCCESS"
export const UPDATE_COUNTRIE_FAIL = "UPDATE_COUNTRIE_FAIL"

export const DELETE_COUNTRIE = "DELETE_COUNTRIE"
export const DELETE_COUNTRIE_SUCCESS = "DELETE_COUNTRIE_SUCCESS"
export const DELETE_COUNTRIE_FAIL = "DELETE_COUNTRIE_FAIL"