/* CITIE */
export const GET_CITIES = "GET_CITIES"
export const GET_CITIES_SUCCESS = "GET_CITIES_SUCCESS"
export const GET_CITIES_FAIL = "GET_CITIES_FAIL"

export const ADD_NEW_CITIE = "ADD_NEW_CITIE"
export const ADD_CITIE_SUCCESS = "ADD_CITIE_SUCCESS"
export const ADD_CITIE_FAIL = "ADD_CITIE_FAIL"

export const UPDATE_CITIE = "UPDATE_CITIE"
export const UPDATE_CITIE_SUCCESS = "UPDATE_CITIE_SUCCESS"
export const UPDATE_CITIE_FAIL = "UPDATE_CITIE_FAIL"

export const DELETE_CITIE = "DELETE_CITIE"
export const DELETE_CITIE_SUCCESS = "DELETE_CITIE_SUCCESS"
export const DELETE_CITIE_FAIL = "DELETE_CITIE_FAIL"