/* CATEGORIE */
export const GET_DELEVERYS = "GET_DELEVERYS"
export const GET_DELEVERYS_SUCCESS = "GET_DELEVERYS_SUCCESS"
export const GET_DELEVERYS_FAIL = "GET_DELEVERYS_FAIL"

export const ADD_NEW_DELEVERY = "ADD_NEW_DELEVERY"
export const ADD_DELEVERY_SUCCESS = "ADD_DELEVERY_SUCCESS"
export const ADD_DELEVERY_FAIL = "ADD_DELEVERY_FAIL"

export const UPDATE_DELEVERY = "UPDATE_DELEVERY"
export const UPDATE_DELEVERY_SUCCESS = "UPDATE_DELEVERY_SUCCESS"
export const UPDATE_DELEVERY_FAIL = "UPDATE_DELEVERY_FAIL"

export const DELETE_DELEVERY = "DELETE_DELEVERY"
export const DELETE_DELEVERY_SUCCESS = "DELETE_DELEVERY_SUCCESS"
export const DELETE_DELEVERY_FAIL = "DELETE_DELEVERY_FAIL"