/* LOCAL */
export const GET_LOCALS = "GET_LOCALS"
export const GET_LOCALS_SUCCESS = "GET_LOCALS_SUCCESS"
export const GET_LOCALS_FAIL = "GET_LOCALS_FAIL"

export const ADD_NEW_LOCAL = "ADD_NEW_LOCAL"
export const ADD_LOCAL_SUCCESS = "ADD_LOCAL_SUCCESS"
export const ADD_LOCAL_FAIL = "ADD_LOCAL_FAIL"

export const UPDATE_LOCAL = "UPDATE_LOCAL"
export const UPDATE_LOCAL_SUCCESS = "UPDATE_LOCAL_SUCCESS"
export const UPDATE_LOCAL_FAIL = "UPDATE_LOCAL_FAIL"

export const DELETE_LOCAL = "DELETE_LOCAL"
export const DELETE_LOCAL_SUCCESS = "DELETE_LOCAL_SUCCESS"
export const DELETE_LOCAL_FAIL = "DELETE_LOCAL_FAIL"